name: Deploy Hugo to GitHub Pages

on:
  # 推送到 master 分支时触发
  push:
    branches: [ "master" ]
  # 允许手动触发
  workflow_dispatch: 

jobs:
  build: # 构建网站任务
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository # 检出代码
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        submodules: false # 如果使用 Git Submodules，改为 true 或 recursive

    - name: Install Nix # 安装 Nix
      uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-24.11 # Nixpkgs 版本

    - name: Build Site # 使用 Nix 构建 Hugo
      run: nix develop --command bash -c "nix run .#build"

    - name: Upload Pages Artifact # 上传 Pages Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./public

  deploy: # 部署网站任务
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
    - name: Deploy to GitHub Pages # 部署到 GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
